apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "event-data-pipeline.fullname" . }}
  annotations:
{{ toYaml .Values.deployment.annotations | indent 4 }}
  labels:
{{ include "event-data-pipeline.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "event-data-pipeline.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
  revisionHistoryLimit: {{.Values.revisionHistoryLimit}}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "event-data-pipeline.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $val := .Values.environment }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: event-data-pipeline-config
            mountPath: /app/configs/{{ .Values.eventDataPipeline.config.filename }}
            subPath: {{ .Values.eventDataPipeline.config.filename }}
          {{- if eq .Values.fluentd.enabled true }}          
          - name: event-data-pipeline-logs-volume
            mountPath: /app/logs/
          {{- end}}
          ports:
          {{- if eq .Values.http.enable true}}
            - name: elc-http
              containerPort: {{ .Values.http.port }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: elc-http
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: elc-http
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          {{- end }}
{{- if eq .Values.fluentd.enabled true }}
        - name: fluentd
          image: {{ .Values.fluentd.image.repository }}:{{ .Values.fluentd.image.tag }}
          imagePullPolicy: {{ .Values.fluentd.image.pullPolicy }}
          resources: 
            {{ toYaml .Values.fluentd.resources | indent 12 }}
          ports:
            - name: fluentd-port
              containerPort: 24224
          livenessProbe:
            httpGet:
              path: /fluentd.healthcheck?json={}
              port: fluentd-port
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /fluentd.healthcheck?json={}
              port: fluentd-port
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
          - name: event-data-pipeline-logs-volume
            mountPath: /app/logs/
          - name: fluentd-service-config
            mountPath: /fluentd/etc/fluent.conf
            subPath: fluent.conf
{{- end}}        
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: event-data-pipeline-config
          configMap:
            name: {{ template "event-data-pipeline.fullname" . }}
{{- if eq .Values.fluentd.enabled true }}        
        - name: fluentd-service-config
          configMap:
            name: {{ template "event-data-pipeline.fullname" . }}
            items:
            - key: fluent.conf
              path: fluent.conf
              mode: 420
        - name: event-data-pipeline-logs-volume
          emptyDir: {}
{{- end }}
