{{- if eq .Values.prometheusOperator.enable true}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "event-data-pipeline.fullname" . }}
  namespace: {{ .Values.prometheusOperator.namespace }}
  labels:
{{ toYaml .Values.prometheusOperator.serviceMonitor.labels | indent 4 }}
    app: {{ template "event-data-pipeline.name" . }}
    chart: {{ template "event-data-pipeline.chart" . }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "event-data-pipeline.name" . }}
      release: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: event-data-pipeline-svc-http
{{- end}}