apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: event-data-pipeline
    app.kubernetes.io/version: 0.1.0
    release: event-data-pipeline
  name: event-data-pipeline
  namespace: default
data:
  config.yaml: |
    - consumer:
        name: kafka
        config:
          max_retries: -1
          retry_delay: 5
          record_check_frequency: 15
          client_name: default
          topic: purchases
          consumer_options:
            bootstrap.servers: "my-cluster-kafka-0.my-cluster-kafka-brokers.kafka.svc:9092"
            group.id: "01"
            auto.offset.reset: earliest
            enable.auto.commit: "false"
            enable.partition.eof: "true"
            session.timeout.ms: "60000"
            heartbeat.interval.ms: "15000"
      processors:
        - name: kafka_default
        - name: kafka_normalizer
      storages:
        - type: filesystem
          config:
            path: fs/
