apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: event-data-pipeline
    release: event-data-pipeline
  name: event-data-pipeline
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: event-data-pipeline
      release: event-data-pipeline
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: event-data-pipeline
        release: event-data-pipeline
    spec:
      containers:
      - env:
        - name: EDP_CONFIG
          value: configs/config.yaml
        - name: EDP_ENABLE_DEBUG_LOGGING
          value: "false"
        - name: EDP_ENABLE_LOGGING_TO_FILE
          value: "true"
        image: youngstone89/event-data-pipeline:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: elc-http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: event-data-pipeline
        ports:
        - containerPort: 8078
          name: elc-http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: elc-http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 200Mi
        volumeMounts:
        - mountPath: /app/configs/config.yaml
          name: event-data-pipeline-config
          subPath: config.yaml
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: event-data-pipeline
        name: event-data-pipeline-config