version: "3.9"
services:
  event-data-pipeline:
    image: ghcr.io/gain620/edp:v1
    environment:
      - EDP_ENABLE_DEBUG_LOGGING=true
      - EDP_CONFIG=configs/config.docker_compose.json
    volumes:
      - ./configs:/app/configs
    networks:
      - edp-net
    depends_on:
      - kafka
      - elasticsearch
networks:
  edp-net:
    driver: bridge